language: node_js
node_js:
  - "0.10"

before_install:
    - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update -qq
    - sudo apt-get install -qq arduino-core arduino-mk
    - sudo apt-get install -qq -y gcc-arm-none-eabi
    - sudo pip install ino
    - git submodule update --init --recursive

script:
    - make
    - npm test
    - make check-release

notifications:
  irc:
    channels:
      - "chat.freenode.net#fbp"
    template:
      - "%{repository}@%{branch} (%{commit}) : %{message} : %{build_url}"
    on_success: change
    on_failure: change
